"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.moderationLogTypes = exports.permissions = exports.ffVisibility = exports.mutedNoteReasons = exports.noteVisibilities = exports.notificationTypes = void 0;
exports.notificationTypes = ['follow', 'mention', 'reply', 'renote', 'quote', 'reaction', 'pollVote', 'pollEnded', 'receiveFollowRequest', 'followRequestAccepted', 'groupInvited', 'app', 'chatMessageReceived'];
exports.noteVisibilities = ['public', 'home', 'followers', 'specified'];
exports.mutedNoteReasons = ['word', 'manual', 'spam', 'other'];
exports.ffVisibility = ['public', 'followers', 'private'];
exports.permissions = [
    'read:account',
    'write:account',
    'read:blocks',
    'write:blocks',
    'read:drive',
    'write:drive',
    'read:favorites',
    'write:favorites',
    'read:following',
    'write:following',
    'read:messaging',
    'write:messaging',
    'read:mutes',
    'write:mutes',
    'write:notes',
    'read:notifications',
    'write:notifications',
    'read:reactions',
    'write:reactions',
    'write:votes',
    'read:pages',
    'write:pages',
    'write:page-likes',
    'read:page-likes',
    'read:user-groups',
    'write:user-groups',
    'read:gallery',
    'write:gallery',
    'read:gallery-likes',
    'write:gallery-likes',
];
exports.moderationLogTypes = [
    'updateServerSettings',
    'suspend',
    'unsuspend',
    'updateUserNote',
    'addCustomEmoji',
    'updateCustomEmoji',
    'deleteCustomEmoji',
    'assignRole',
    'unassignRole',
    'createRole',
    'updateRole',
    'deleteRole',
    'clearQueue',
    'promoteQueue',
    'deleteDriveFile',
    'deleteNote',
    'createGlobalAnnouncement',
    'createUserAnnouncement',
    'updateGlobalAnnouncement',
    'updateUserAnnouncement',
    'deleteGlobalAnnouncement',
    'deleteUserAnnouncement',
    'resetPassword',
    'suspendRemoteInstance',
    'unsuspendRemoteInstance',
    'markSensitiveDriveFile',
    'unmarkSensitiveDriveFile',
    'resolveAbuseReport',
    'createInvitation',
    'createAd',
    'updateAd',
    'deleteAd',
    'createAvatarDecoration',
    'updateAvatarDecoration',
    'deleteAvatarDecoration',
];
//# sourceMappingURL=consts.js.map